[metadata]
name = demosat-fresh
version = attr: demosat_fresh.__version__
author = Matt Muszynski
license = Caltech (JPL)

[options]
python_requires = >= 3.6
packages = find:
package_dir = 
    = src
include_package_data = True
install_requires = 
    arrow==1.2.3
    colorama
    lxml
    dataclasses;python_version<'3.7'

[options.extras_require]
dev =
    pytest
    build
    twine

[options.packages.find]
where = src
exclude = test

[options.package_data]
* =
    *.csv
    *.json

[options.entry_points]
console_scripts =
    fresh = fresh.run_fresh:main
